# Site settings
title: Flybase
email: hello@flybase.io
description: Build Real-time Apps
longdescription: > # this means to ignore newlines until "baseurl:"
  The Flybase Blog is the official online publication written by the founders and developers of 
  Flybase about their real-time app platform, related technologies, and whatever else may fit 
  their fancy — like robots!baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://flybase.io" # the base hostname & protocol for your site
twitter_username: flybaseio
github_username:  flybaseio

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  